"""
ArogyaTwin evaluation simulator.

A discrete-time (1-hour tick) simulation of a 6-village rural surveillance
region, used to generate the experimental results reported in Sections 5-6
of the manuscript. This is a controlled synthetic-data simulation, not a
field deployment -- all ground truth (true outbreak labels, degraded/attack
behavior) is generated by this script and used only for evaluation.

Reproducibility: every run is driven by a single integer seed. All
scenario, source, trust, and TTL parameters are listed in CONFIG below and
are also reported in the manuscript (Section 5).
"""
import numpy as np

# ----------------------------------------------------------------------
# Global configuration (reported in manuscript Table 5)
# ----------------------------------------------------------------------
N_VILLAGES = 6
SOURCES_PER_VILLAGE = 5          # healthcare, school, pharmacy, env-sensor, community
N_SOURCES = N_VILLAGES * SOURCES_PER_VILLAGE
HOURS = 720                       # 30-day evaluation horizon

OUTBREAK_1 = dict(village=1, onset=300, duration=150, ramp=12, p_fire=0.40, true_frac=0.85)
OUTBREAK_2 = dict(village=4, onset=480, duration=120, ramp=12, p_fire=0.40, true_frac=0.85)
DEGRADED_VILLAGE = 5               # chronic low-quality / noisy village
ADVERSARIAL_VILLAGE = 2             # briefly poisoned village
ADVERSARIAL_WINDOW = (192, 216)     # hour range of the poisoning burst (day 8-9)

P_BASE = 0.04                       # baseline per-source firing probability/hour
P_DEGRADED_BASE = 0.12              # elevated baseline firing rate for degraded village
P_ADVERSARIAL_BURST = 0.55          # firing probability during poisoning burst

# Trust model weights (selected configuration; no grid-search code in this repository)
TRUST_WEIGHTS = dict(w_H=0.35, w_C=0.20, w_A=0.30, w_D=0.15)
H_ALPHA = 0.20                      # EMA rate for historical verification
H_PRIOR = 0.60
VERIFICATION_DELAY = 48             # hours until ground-truth feedback resolves

# TTL model (calibrated parameters B_L, B_T; see Section 6.5 / Table 6)
TTL_MIN, TTL_MAX = 2, 96
K_ROUTINE, K_CANDIDATE = 1.5, 3.0
TTL_MAX_ROUTINE, TTL_MAX_CANDIDATE = 48, 96
B_L, B_T = 0.35, 10.0                # calibrated via grid search (Section 6.5 / Table 6)
LONG_TERM_WINDOW, SHORT_TERM_WINDOW = 10, 3

# Packet sizes (bytes) -- concrete schema, see Table 5 (evidence packet)
COMPACT_SIZE_BYTES = 64
RAW_SIZE_BYTES = 512

CANDIDATE_MIN_SOURCES = 3
CANDIDATE_MIN_CONF = 0.5

SCENARIOS = {
    "connected_baseline": dict(mean_contact=2, outage_windows=[]),
    "short_outage":       dict(mean_contact=4, outage_windows=[(150, 162), (350, 362), (550, 562)]),
    "long_outage":        dict(mean_contact=6, outage_windows=[(288, 384)]),  # overlaps outbreak-1
    "high_latency":       dict(mean_contact=6, outage_windows=[], extra_latency=10),
    "low_trust_source":   dict(mean_contact=4, outage_windows=[]),
    "multi_source_agree": dict(mean_contact=4, outage_windows=[]),
    "mixed_validity":     dict(mean_contact=5, outage_windows=[(250, 270)]),
    "adversarial":        dict(mean_contact=4, outage_windows=[]),
}


def clip(x, lo, hi):
    return np.minimum(np.maximum(x, lo), hi)


def village_of(source_idx):
    return source_idx // SOURCES_PER_VILLAGE


def generate_ground_truth(rng):
    """Per (source, hour) firing indicator, true_label, extraction confidence, and
    source-accuracy ground truth.

    true_label:  whether the firing reflects a genuine outbreak-relevant signal
                 (used for detection precision/recall).
    accurate:    whether the firing is a legitimate, honestly-obtained observation
                 from that source (used as the ground-truth feedback signal for the
                 historical-verification trust term H). A normal village reporting
                 routine, non-outbreak activity is still an *accurate* report -- it
                 correctly reflects that nothing unusual is happening. Only the
                 chronically degraded village and the briefly poisoned village
                 (during its attack window) produce inaccurate/fabricated reports.
    """
    fire = np.zeros((N_SOURCES, HOURS), dtype=bool)
    true_label = np.zeros((N_SOURCES, HOURS), dtype=bool)
    accurate = np.zeros((N_SOURCES, HOURS), dtype=bool)
    conf = np.zeros((N_SOURCES, HOURS), dtype=float)

    village_quality = {v: (9, 2) for v in range(N_VILLAGES)}
    village_quality[DEGRADED_VILLAGE] = (3, 6)

    for s in range(N_SOURCES):
        v = village_of(s)
        for t in range(HOURS):
            p = P_BASE
            if v == DEGRADED_VILLAGE:
                p = P_DEGRADED_BASE
            for ob in (OUTBREAK_1, OUTBREAK_2):
                if v == ob["village"]:
                    t0, t1 = ob["onset"], ob["onset"] + ob["duration"]
                    if t0 <= t < t1:
                        ramp = ob["ramp"]
                        if t - t0 < ramp:
                            w = (t - t0) / ramp
                        elif t1 - t < ramp:
                            w = (t1 - t) / ramp
                        else:
                            w = 1.0
                        p = max(p, ob["p_fire"] * w)
            if v == ADVERSARIAL_VILLAGE and ADVERSARIAL_WINDOW[0] <= t < ADVERSARIAL_WINDOW[1]:
                p = P_ADVERSARIAL_BURST

            if rng.random() < p:
                fire[s, t] = True
                a, b = village_quality[v]
                is_adversarial_burst = (v == ADVERSARIAL_VILLAGE and
                                         ADVERSARIAL_WINDOW[0] <= t < ADVERSARIAL_WINDOW[1])
                if is_adversarial_burst:
                    conf[s, t] = rng.beta(9, 1)  # attacker fakes high confidence
                    true_label[s, t] = False
                    accurate[s, t] = False
                elif v == DEGRADED_VILLAGE:
                    conf[s, t] = rng.beta(a, b)
                    true_label[s, t] = False
                    accurate[s, t] = False
                else:
                    conf[s, t] = rng.beta(a, b)
                    in_outbreak = False
                    for ob in (OUTBREAK_1, OUTBREAK_2):
                        if v == ob["village"] and ob["onset"] <= t < ob["onset"] + ob["duration"]:
                            in_outbreak = True
                    if in_outbreak:
                        true_label[s, t] = rng.random() < ob["true_frac"]
                    else:
                        true_label[s, t] = False
                    accurate[s, t] = True  # honestly-obtained report, whether or not it is outbreak-relevant
    return fire, true_label, conf, accurate


def village_drift(t):
    """Latent telemetry-drift ground-truth process D_i(t), per village, in [0,1]."""
    d = np.full(N_VILLAGES, 0.05)
    d[DEGRADED_VILLAGE] = 0.50
    if ADVERSARIAL_WINDOW[0] <= t < ADVERSARIAL_WINDOW[1]:
        d[ADVERSARIAL_VILLAGE] = 0.60
    return d


def contact_process(rng, scenario_cfg):
    """Per-village boolean contact-opportunity trace over HOURS."""
    mean_c = scenario_cfg["mean_contact"]
    p = 1.0 / mean_c
    contact = rng.random((N_VILLAGES, HOURS)) < p
    for (t0, t1) in scenario_cfg.get("outage_windows", []):
        contact[:, t0:t1] = False
    return contact
